fusion_df <- read.table("data/fusion_df.txt", header=T, stringsAsFactors=F)
all_samples <- read.table("data/sample_list.806.txt", header=F, stringsAsFactors=F)
names(all_samples) <- c("MMRF","SRR")
samples <- read.table("data/sample_list.primary.txt", header=F, stringsAsFactors=F)
names(samples) <- c("MMRF","SRR")
expr <- read.table("data/mmy_gene_expr_with_fusions.tsv", header=T, stringsAsFactors=F)
primary_df <- subset(fusion_df, sample_number==1)
clinical_df <- read.table("data/clinical_df.tsv", header=T, stringsAsFactors=F)
seqfish_df <- read.table("data/seqfish_df.tsv", header=T, stringsAsFactors=F)